name: WhatColors BackEnd

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to cloud server
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command: |
            git clone https://github.com/Z4nR/WhatColors
            cd ~/WhatColors/server
            git pull origin main
            cd server
            docker compose down --remove-orphans
            docker compose up --build -d
